DEFINE SCHEMA_NAME = &1;
DEFINE SCHEMA_PASSWORD = &2;

alter session set container = orclpdb1;

create user &&SCHEMA_NAME identified by &&SCHEMA_PASSWORD;

GRANT CREATE SESSION TO &&SCHEMA_NAME;
GRANT CREATE ANY TABLE TO &&SCHEMA_NAME;
GRANT ALTER ANY TABLE TO &&SCHEMA_NAME;
GRANT DROP ANY TABLE TO &&SCHEMA_NAME;
GRANT INSERT ANY TABLE TO &&SCHEMA_NAME;
GRANT SELECT ANY TABLE TO &&SCHEMA_NAME;
GRANT UPDATE ANY TABLE TO &&SCHEMA_NAME;
GRANT DELETE ANY TABLE TO &&SCHEMA_NAME;
GRANT CREATE MATERIALIZED VIEW TO &&SCHEMA_NAME;
GRANT CREATE ANY VIEW TO &&SCHEMA_NAME;
GRANT CREATE ANY SEQUENCE TO &&SCHEMA_NAME;
GRANT CREATE ANY TRIGGER TO &&SCHEMA_NAME;
GRANT CREATE ANY PROCEDURE TO &&SCHEMA_NAME;
GRANT EXECUTE ANY PROCEDURE TO &&SCHEMA_NAME;
GRANT CREATE ANY INDEX TO &&SCHEMA_NAME;
GRANT ALTER ANY INDEX TO &&SCHEMA_NAME;
GRANT DROP ANY INDEX TO &&SCHEMA_NAME;
GRANT CREATE ANY TRIGGER TO &&SCHEMA_NAME;
GRANT ALTER ANY TRIGGER TO &&SCHEMA_NAME;
GRANT DROP ANY TRIGGER TO &&SCHEMA_NAME;
GRANT CREATE ROLE TO &&SCHEMA_NAME;
GRANT COMMENT ANY TABLE TO &&SCHEMA_NAME;
GRANT GRANT ANY OBJECT PRIVILEGE TO &&SCHEMA_NAME;
GRANT CREATE USER TO &&SCHEMA_NAME;
GRANT SELECT ANY DICTIONARY TO &&SCHEMA_NAME;
GRANT UNLIMITED TABLESPACE TO &&SCHEMA_NAME;
GRANT DEBUG CONNECT SESSION TO &&SCHEMA_NAME;
GRANT DEBUG ANY PROCEDURE TO &&SCHEMA_NAME;
GRANT DEBUG CONNECT ANY TO &&SCHEMA_NAME;
