choco upgrade microsoft-windows-terminal --yes
choco upgrade notepadplusplus.install --yes
choco upgrade powershell-core --yes
choco upgrade 7zip --yes
choco upgrade teracopy --yes
choco upgrade microsoft-teams --yes
choco upgrade clipx --yes
choco upgrade drawio --yes
choco upgrade googlechrome --yes
choco upgrade lastpass-chrome --yes
choco upgrade openvpn-connect --yes
choco upgrade autohotkey --yes